### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by JIEUN-12** [addb-swstarlab/OANet#1]
Hi. I'm interested in database performance prediction models.

I wonder what the dataset looks like. 
And are the databases using RocksDB? It is hard to recognize which database is used.

I would be glad if you comment on these.

**Comment by DELAB-Y** [comment]
The dataset consists of data for multiple workloads environment.
And each row of the dataset for each workload consists of Knob configuration values and performance values 

That's right. We used RocksDB in our experiments. 
But OANet can also use another database too.
