### ISSUE TITLE
About model Hyper parameter.

### ISSUE THREAD

**Issue by Hyunjining** [addb-swstarlab/OANet#6]
Hello,

How did you set the hyperparameters for the epoch value of 30 and the batch size value of 64?

I was wondering if you experimented with changing the epoch and batch size to different values.

Thanks for reading.

**Comment by DELAB-Y** [comment]
Hello, thanks for interesting on our works!

The value on the GitHub code(e.g.  epoch :30, batch_size:64) is just default value that goes into the argpaser and it's not the value that we actually used.

So when you run the codes,  you have to specify the value when you experiment.

And We experimented by changing the parameter values.

Thanks for reading.
