### ISSUE TITLE
Where is dataset?

### ISSUE THREAD

**Issue by kimkyeonghun** [addb-swstarlab/OANet#7]
I want your dataset when training OANet.

If you don't want to open dataset public, please send dataset to my email

My email is kkh115505@gmail.com

**Comment by Ychanho** [comment]
We used a dataset that ran the dbbench benchmark on rocksdb when taining OANet.
And the values in that dataset also vary depending on the performance of the hardware that runs the benchmark for that database. And the generating dataset is now available with code in 'Rocksdb-data-generation' repository

https://github.com/addb-swstarlab/RocksDB-data-generation
