### ISSUE TITLE
Question about attention calculation

### ISSUE THREAD

**Issue by SkiddieAhn** [addb-swstarlab/OANet#8]
Upon reviewing the OANet paper, I noticed the equations for attention. However, when checking the code, it uses multi-head attention (MHA). Could you provide additional explanation on how MHA is implemented?

**Comment by Ychanho** [comment]
If you give the number of heads in a multi-head attention class to 1, the result is the same as a normal attention class. I wrote the code so that it would be easier to modify in case of further improvements to the model later.
